# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'model.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmodel.proto\x12\x05model\"\x1f\n\x0cModelRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\"\x85\x01\n\rModelResponse\x12>\n\rprobabilities\x18\x01 \x03(\x0b\x32\'.model.ModelResponse.ProbabilitiesEntry\x1a\x34\n\x12ProbabilitiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\x32\x43\n\x0cModelService\x12\x33\n\x06\x44\x65tect\x12\x13.model.ModelRequest\x1a\x14.model.ModelResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODELRESPONSE_PROBABILITIESENTRY']._loaded_options = None
  _globals['_MODELRESPONSE_PROBABILITIESENTRY']._serialized_options = b'8\001'
  _globals['_MODELREQUEST']._serialized_start=22
  _globals['_MODELREQUEST']._serialized_end=53
  _globals['_MODELRESPONSE']._serialized_start=56
  _globals['_MODELRESPONSE']._serialized_end=189
  _globals['_MODELRESPONSE_PROBABILITIESENTRY']._serialized_start=137
  _globals['_MODELRESPONSE_PROBABILITIESENTRY']._serialized_end=189
  _globals['_MODELSERVICE']._serialized_start=191
  _globals['_MODELSERVICE']._serialized_end=258
# @@protoc_insertion_point(module_scope)
